// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-tokens.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-tokens.ts
var list_tokens_default = defineTool({
  name: "list_tokens",
  title: "List tokens",
  description: "List the SPL tokens launched by the autonomous AI mind, newest first or ranked by 24h volume.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many tokens to return."),
    sort: z.enum(["newest", "volume"]).default("newest").describe("Order results by launch time or by 24h volume.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, sort }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("tokens").select("id, name, symbol, price, supply, holders, liquidity, volume_24h, mint_address, launch_timestamp, created_at").order(sort === "volume" ? "volume_24h" : "created_at", { ascending: false }).limit(limit ?? 10);
    if (error) throw new ToolError(error.message);
    const tokens = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: tokens.length ? tokens.map(
            (t) => `${t.symbol} \u2014 ${t.name} | price ${t.price} | 24h vol ${t.volume_24h} | holders ${t.holders} | launched ${t.launch_timestamp}`
          ).join("\n") : "No tokens have been launched yet."
        }
      ],
      structuredContent: { tokens }
    };
  }
});

// src/lib/mcp/tools/get-token.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_token_default = defineTool2({
  name: "get_token",
  title: "Get token details",
  description: "Get full public details for one token by ticker symbol or id, including price, supply, holders and bonding-curve data.",
  inputSchema: {
    symbol: z2.string().trim().min(1).optional().describe("Ticker symbol, e.g. QM."),
    id: z2.string().uuid().optional().describe("Token id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, id }) => {
    if (!symbol && !id) throw new ToolError2("Provide either a symbol or an id.");
    const supabase = supabaseAnon();
    let query = supabase.from("tokens").select("*").limit(1);
    query = id ? query.eq("id", id) : query.ilike("symbol", symbol);
    const { data, error } = await query.maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No token found for ${id ?? symbol}.`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { token: data }
    };
  }
});

// src/lib/mcp/tools/recent-activity.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.4.3";
var recent_activity_default = defineTool3({
  name: "recent_activity",
  title: "Recent protocol activity",
  description: "Read the most recent public protocol activity events (mints, trades, AI decisions, lottery draws).",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("How many events to return."),
    activity_type: z3.string().trim().min(1).optional().describe("Optional filter on the activity type, e.g. ai_mind_analysis.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, activity_type }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("protocol_activity").select("id, activity_type, description, token_id, timestamp").order("timestamp", { ascending: false }).limit(limit ?? 20);
    if (activity_type) query = query.eq("activity_type", activity_type);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    const events = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: events.length ? events.map((e) => `[${e.timestamp}] ${e.activity_type}: ${e.description}`).join("\n") : "No protocol activity recorded yet."
        }
      ],
      structuredContent: { events }
    };
  }
});

// src/lib/mcp/tools/protocol-stats.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.28.0";
var protocol_stats_default = defineTool4({
  name: "protocol_stats",
  title: "Protocol stats",
  description: "Aggregate public protocol stats: total tokens launched, combined 24h volume, liquidity and holder count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("tokens").select("volume_24h, liquidity, holders, created_at");
    if (error) throw new ToolError4(error.message);
    const tokens = data ?? [];
    const sum = (pick) => tokens.reduce((acc, t) => acc + Number(pick(t) || 0), 0);
    const sortedDates = tokens.map((t) => String(t.created_at)).sort();
    const latest = sortedDates.length ? sortedDates[sortedDates.length - 1] : void 0;
    const stats = {
      total_tokens: tokens.length,
      total_volume_24h: sum((t) => t.volume_24h),
      total_liquidity: sum((t) => t.liquidity),
      total_holders: sum((t) => t.holders),
      last_launch_at: latest ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "auto-spl-mint",
  title: "auto-spl-mint",
  version: "0.1.0",
  instructions: "Read-only tools for the autonomous SPL token launcher. Use `list_tokens` to browse launched tokens, `get_token` for one token's details, `recent_activity` for the protocol event stream, and `protocol_stats` for aggregate metrics. All data is public.",
  tools: [list_tokens_default, get_token_default, recent_activity_default, protocol_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
